chore(deps): update dependencies and settings for CKAN 2.11 compatibility
GenomicDataInfrastructure/gdi-userportal-ckan-docker pull request #123
Opened 2024-09-24 12:21 UTC by Markus92

New DCAT extension is required

New harvest extension is necessary. There is no release yet (latest release is June '23), so tagged the latest current commit in master branch

`recline_view` plugin is unsupported in 2.11, so replaced with `datatables_view`

Due to being debian-based, using apt-get to install dependencies. supervisor is done in base image, we need to add postgres client for loading the translations table. cron is not installed by default and I cannot test atm how well it'll work.

Some more changes might be necessary, but a first smoketest with this seems to work.

2024-09-27 07:43 UTC, brunopacheco1 commented on ckan/Dockerfile
> +FROM ckan/ckan-base:2.11
important: the same comments done on `Dockerfile.dev` are applied for this file.

2024-09-27 07:45 UTC, brunopacheco1 requested changes
important: let's wait a bit more to integrate these changes, as they impact the whole system, and we have soon enough a release to do.

2024-09-27 08:29 UTC, Markus92 commented on ckan/Dockerfile.dev
> +# # Install cron and postgres client
Postgres client is necessary for the upload_vocabulary script, which uses the psql command. CKAN works without it.

2024-09-27 08:30 UTC, Markus92 commented on ckan/Dockerfile.dev
> +ENV CKAN__PLUGINS="envvars image_view datatables_view text_view scheming_datasets scheming_organizations gdi_userportal dcat harvest ckan_harvester dcat_rdf_harvester dcat_json_harvester dcat_json_in
We don't need any of those. The dcat_json harvesters/interface can also be removed.

2024-09-27 08:48 UTC, Markus92 commented
Fixed the issues. I'd still advise waiting for merging this in until ckanext-dcat 2.0 scheming and changes are prepared.

2024-11-21 21:01 UTC, brunopacheco1 commented
Hey @Markus92 , just to let you know the new harvest release is out there and our ckan-docker has it installed, and also latest dcat extension, fair-datapoint and scheming changes.

Could you please also pay attention to the impacts on UI? We have made quite a lot of theme changes, that may not work correctly anymore.

2024-11-21 21:06 UTC, brunopacheco1 commented on ckan/Dockerfile.dev
> +ENV CKAN__PLUGINS="envvars image_view datatables_view text_view scheming_datasets scheming_organizations gdi_userportal dcat harvest ckan_harvester dcat_rdf_harvester dcat_json_harvester dcat_json_in
If we are sure we don't use none of these, and there is not dependency on them from other extensions, indeed we could simply remove them all.

2024-11-22 12:59 UTC, hcvdwerf commented
> @hcvdwerf didn't you already take a look at this?

not yet, but require only settings the versions correct and do some tests

2024-11-27 08:14 UTC, merged