chore: Update CI/CD pipelines
GenomicDataInfrastructure/gdi-userportal-ckan-docker pull request #38
Opened 2024-01-26 20:27 UTC by brunopacheco1

2024-01-29 09:46 UTC, hcvdwerf requested changes

2024-01-29 09:46 UTC, hcvdwerf commented on .github/workflows/release.yml
> +          title: MyReleaseMessage
This looks not finished yet

2024-01-30 10:09 UTC, brunopacheco1 commented on .github/workflows/release.yml
> +          title: MyReleaseMessage
Fixed.

2024-01-30 10:17 UTC, admy7 approved these changes

2024-01-30 10:18 UTC, hcvdwerf approved these changes

2024-01-30 10:18 UTC, merged